name: eosdart
description: EOSIO-based blockchain RPC API client in Dart language
version: 0.4.7
homepage: https://github.com/primes-network/eosdart

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  json_annotation: ^4.0.1
  pointycastle: ^1.0.1
  eosdart_ecc:
    git:
      url: https://github.com/JoinSEEDS/eosdart_ecc.git
      
dev_dependencies:
  test: ^1.16.8
  json_serializable: ^4.1.0
